server:   
  context-path: /micro   
  port: 8080 

spring:   
  cloudant:     
    username: ${vcap.services.Cloudant-bala-db.credentials.username}
    password: ${vcap.services.Cloudant-bala-db.credentials.password}     
    host: ${vcap.services.Cloudant-bala-db.credentials.host}     
    protocol: https     
    port: 443     
    database: customers
  